<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net8.0;netstandard2.1</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <LangVersion>12</LangVersion>
        <RootNamespace>Deterministic.GameFramework.Navigation2D</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Core\Deterministic.GameFramework.ECS\Deterministic.GameFramework.ECS.csproj" />
        <ProjectReference Include="..\..\Deterministic.GameFramework.SourceGenerators\Deterministic.GameFramework.SourceGenerators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
        <ProjectReference Include="..\Deterministic.GameFramework.TwoD\Deterministic.GameFramework.TwoD.csproj" />
        <ProjectReference Include="..\Deterministic.GameFramework.TwoD.Physics\Deterministic.GameFramework.TwoD.Physics.csproj" />
    </ItemGroup>

    <ItemGroup>
      <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
        <_Parameter1>Deterministic.GameFramework.Navigation.Tests</_Parameter1>
      </AssemblyAttribute>
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
      <PackageReference Include="GodotSharp" Version="4.3.0" />
    </ItemGroup>

    <PropertyGroup Condition="'$(TargetFramework)' == 'net8.0'">
        <DefineConstants>$(DefineConstants);GODOT</DefineConstants>
    </PropertyGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.1'">
        <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    </ItemGroup>

</Project>
