using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Deterministic.GameFramework.SourceGenerators
{
    [Generator]
    public class NetworkIdGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // Filter classes/structs that might have the NetworkId attribute
            IncrementalValuesProvider<TypeDeclarationSyntax> typeDeclarations = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (s, _) => IsSyntaxTargetForGeneration(s),
                    transform: static (ctx, _) => GetSemanticTargetForGeneration(ctx))
                .Where(static m => m is not null)!;

            // Combine with compilation
            IncrementalValueProvider<(Compilation, ImmutableArray<TypeDeclarationSyntax>)> compilationAndTypes
                = context.CompilationProvider.Combine(typeDeclarations.Collect());

            // Generate the source
            context.RegisterSourceOutput(compilationAndTypes,
                static (spc, source) => Execute(source.Item1, source.Item2, spc));
        }

        private static bool IsSyntaxTargetForGeneration(SyntaxNode node)
            => node is TypeDeclarationSyntax { AttributeLists.Count: > 0 };

        private static TypeDeclarationSyntax? GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
        {
            var typeDeclaration = (TypeDeclarationSyntax)context.Node;
            foreach (var attributeList in typeDeclaration.AttributeLists)
            {
                foreach (var attribute in attributeList.Attributes)
                {
                    if (context.SemanticModel.GetSymbolInfo(attribute).Symbol is IMethodSymbol attributeSymbol)
                    {
                        var attributeContainingTypeSymbol = attributeSymbol.ContainingType;
                        var fullName = attributeContainingTypeSymbol.ToDisplayString();

                        if (fullName == "Deterministic.GameFramework.CoreV2.NetworkIdAttribute" || 
                            fullName == "Deterministic.GameFramework.CoreV2.NetworkId")
                        {
                            return typeDeclaration;
                        }
                    }
                }
            }
            return null;
        }

        private static void Execute(Compilation compilation, ImmutableArray<TypeDeclarationSyntax> types, SourceProductionContext context)
        {
            if (types.IsDefaultOrEmpty) return;

            var typeIdMap = new Dictionary<string, int>();

            foreach (var typeDeclaration in types.Distinct())
            {
                var semanticModel = compilation.GetSemanticModel(typeDeclaration.SyntaxTree);
                if (semanticModel.GetDeclaredSymbol(typeDeclaration) is INamedTypeSymbol typeSymbol)
                {
                    var attributes = typeSymbol.GetAttributes();
                    var networkIdAttr = attributes.FirstOrDefault(a => 
                        a.AttributeClass?.ToDisplayString() == "Deterministic.GameFramework.CoreV2.NetworkIdAttribute" ||
                        a.AttributeClass?.ToDisplayString() == "Deterministic.GameFramework.CoreV2.NetworkId");

                    if (networkIdAttr != null && networkIdAttr.ConstructorArguments.Length > 0)
                    {
                        if (networkIdAttr.ConstructorArguments[0].Value is int id)
                        {
                            typeIdMap[typeSymbol.ToDisplayString()] = id;
                        }
                    }
                }
            }

            if (typeIdMap.Count == 0) return;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using Deterministic.GameFramework.CoreV2;");
            sb.AppendLine("");
            sb.AppendLine("[assembly: Deterministic.GameFramework.Generated.NetworkIdRegistry.RegisterAttribute]");
            sb.AppendLine("");
            sb.AppendLine("namespace Deterministic.GameFramework.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    public static partial class NetworkIdRegistry");
            sb.AppendLine("    {");
            sb.AppendLine("        public class RegisterAttribute : Attribute {}");
            sb.AppendLine("");
            sb.AppendLine("        public static void RegisterAll()");
            sb.AppendLine("        {");
            sb.AppendLine("            Console.WriteLine($\"[NetworkIdRegistry] Registering {IdToType.Count} types from {typeof(NetworkIdRegistry).Assembly.GetName().Name}...\");");
            sb.AppendLine("            foreach (var kvp in IdToType)");
            sb.AppendLine("            {");
            sb.AppendLine("                ComponentTypeRegistry.GetOrRegister(kvp.Key, kvp.Value);");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("");
            sb.AppendLine("        public static readonly Dictionary<Type, int> TypeToId = new Dictionary<Type, int>()");
            sb.AppendLine("        {");

            foreach (var kvp in typeIdMap)
            {
                sb.AppendLine($"            {{ typeof({kvp.Key}), {kvp.Value} }},");
            }

            sb.AppendLine("        };");
            sb.AppendLine("");
            sb.AppendLine("        public static readonly Dictionary<int, Type> IdToType = new Dictionary<int, Type>()");
            sb.AppendLine("        {");

            foreach (var kvp in typeIdMap)
            {
                sb.AppendLine($"            {{ {kvp.Value}, typeof({kvp.Key}) }},");
            }

            sb.AppendLine("        };");
            sb.AppendLine("");
            sb.AppendLine("        public static int GetId<T>() => TypeToId[typeof(T)];");
            sb.AppendLine("        public static Type GetType(int id) => IdToType[id];");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            context.AddSource("NetworkIdRegistry.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }
    }
}