<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>12.0</LangVersion>
        <TargetFrameworks>net8.0;netstandard2.1</TargetFrameworks>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Deterministic.GameFramework.Types\Deterministic.GameFramework.Types.csproj" />
      <ProjectReference Include="..\Deterministic.GameFramework.Utils\Deterministic.GameFramework.Utils.csproj" />
    </ItemGroup>

    <ItemGroup>
      <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
        <_Parameter1>Deterministic.GameFramework.ECS.Tests</_Parameter1>
      </AssemblyAttribute>
    </ItemGroup>

</Project>
