<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <TargetFrameworks>net8.0;netstandard2.1</TargetFrameworks>
        <LangVersion>12</LangVersion>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="ObservableCollections" Version="3.3.4" />
      <PackageReference Include="R3" Version="1.3.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Deterministic.GameFramework.ECS\Deterministic.GameFramework.ECS.csproj" />
      <ProjectReference Include="..\Deterministic.GameFramework.Common\Deterministic.GameFramework.Common.csproj" />
    </ItemGroup>

</Project>
