<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net8.0;netstandard2.1</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <LangVersion>12</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Deterministic.GameFramework.CoreV2\Deterministic.GameFramework.CoreV2.csproj" />
        <ProjectReference Include="..\Deterministic.GameFramework.Reactive\Deterministic.GameFramework.Reactive.csproj" />
        <ProjectReference Include="..\Deterministic.GameFramework.SourceGenerators\Deterministic.GameFramework.SourceGenerators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
      <PackageReference Include="GodotSharp" Version="4.3.0" />
    </ItemGroup>
    
    <PropertyGroup Condition="'$(TargetFramework)' == 'net8.0'">
        <DefineConstants>$(DefineConstants);GODOT</DefineConstants>
    </PropertyGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.1'">
        <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    </ItemGroup>

    <ItemGroup>
        <None Include="external\librapier_uniffi.dylib" Link="librapier_uniffi.dylib">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <Pack>true</Pack>
            <PackagePath>runtimes/osx/native/</PackagePath>
        </None>
        <!-- Add other platforms here if available, e.g. .dll for Windows, .so for Linux -->
    </ItemGroup>

</Project>
