<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net8.0;netstandard2.1</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <LangVersion>12</LangVersion>
        <RootNamespace>Deterministic.GameFramework.Detour</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Core\Deterministic.GameFramework.Types\Deterministic.GameFramework.Types.csproj" />
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.1'">
        <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    </ItemGroup>

</Project>
