<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>12.0</LangVersion>
        <TargetFrameworks>net8.0;netstandard2.1</TargetFrameworks>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="FixedMathSharp" Version="2.1.0" />
      <PackageReference Include="System.Text.Json" Version="8.0.0" Condition="'$(TargetFramework)' == 'netstandard2.1'" />
    </ItemGroup>

</Project>
