<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>Deterministic.GameFramework.TwoD</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>12.0</LangVersion>
        <TargetFrameworks>net8.0;netstandard2.1</TargetFrameworks>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Core\Deterministic.GameFramework.ECS\Deterministic.GameFramework.ECS.csproj" />
    </ItemGroup>

</Project>
