<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net8.0;netstandard2.1</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>12.0</LangVersion>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Deterministic.GameFramework.Common\Deterministic.GameFramework.Common.csproj" />
      <ProjectReference Include="..\Deterministic.GameFramework.Debugging\Deterministic.GameFramework.Debugging.csproj" />
      <ProjectReference Include="..\Deterministic.GameFramework.ECS\Deterministic.GameFramework.ECS.csproj" />
      <ProjectReference Include="..\Deterministic.GameFramework.Serialization\Deterministic.GameFramework.Serialization.csproj" />
      <ProjectReference Include="..\Deterministic.GameFramework.DAR\Deterministic.GameFramework.DAR.csproj" />
      <ProjectReference Include="..\..\Networking\Deterministic.GameFramework.Network\Deterministic.GameFramework.Network.csproj" />
    </ItemGroup>

</Project>
