using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Deterministic.GameFramework.SourceGenerators
{
    [Generator]
    public class ActionGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var components = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: (node, _) => node is StructDeclarationSyntax,
                    transform: (ctx, _) => GetComponentInfo(ctx))
                .Where(m => m != null);

            context.RegisterSourceOutput(components, Execute);
        }

        private static ComponentInfo? GetComponentInfo(GeneratorSyntaxContext context)
        {
            var structDeclaration = (StructDeclarationSyntax)context.Node;
            var symbol = context.SemanticModel.GetDeclaredSymbol(structDeclaration);
            
            if (symbol == null) return null;

            // Check if implements IComponent
            if (!symbol.AllInterfaces.Any(i => i.Name == "IComponent"))
            {
                return null;
            }

            var namespaceName = symbol.ContainingNamespace.ToDisplayString();
            var structName = symbol.Name;
            
            var fields = symbol.GetMembers()
                .OfType<IFieldSymbol>()
                .Where(f => f.DeclaredAccessibility == Accessibility.Public && !f.IsStatic)
                .Where(f => f.GetAttributes().Any(a => a.AttributeClass?.Name == "AutoActionAttribute" || a.AttributeClass?.Name == "AutoAction"))
                .Select(f => new FieldInfo 
                { 
                    Name = f.Name, 
                    Type = f.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) 
                })
                .ToList();

            if (fields.Count == 0) return null;

            return new ComponentInfo
            {
                Namespace = namespaceName,
                StructName = structName,
                Fields = fields
            };
        }

        private void Execute(SourceProductionContext context, ComponentInfo? info)
        {
            if (info == null) return;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using System;");
            sb.AppendLine("using Deterministic.GameFramework.CoreV2;");
            sb.AppendLine("");
            sb.AppendLine($"namespace {info.Namespace}");
            sb.AppendLine("{");

            foreach (var field in info.Fields)
            {
                var actionName = $"Set{field.Name}Action";
                var serviceName = $"{actionName}Service";
                var componentFullName = info.StructName; 
                var fieldType = field.Type;

                // 1. Generate Action Struct
                sb.AppendLine($"    public struct {actionName} : IAction");
                sb.AppendLine("    {");
                sb.AppendLine($"        public {fieldType} {field.Name};");
                sb.AppendLine("");
                sb.AppendLine($"        public {actionName}({fieldType} value)");
                sb.AppendLine("        {");
                sb.AppendLine($"            {field.Name} = value;");
                sb.AppendLine("        }");
                sb.AppendLine("    }");
                sb.AppendLine("");

                // 2. Generate Action Service
                // Calculate stable NetworkId
                var stableHashString = $"{info.Namespace}.{serviceName}";
                var networkId = Math.Abs(GetStableHashCode(stableHashString));
                
                sb.AppendLine($"    [NetworkId({networkId})]");
                sb.AppendLine($"    public class {serviceName} : ActionService<{actionName}, {componentFullName}>");
                sb.AppendLine("    {");
                sb.AppendLine($"        protected override void ExecuteProcess({actionName} action, ref {componentFullName} component, Context ctx)");
                sb.AppendLine("        {");
                sb.AppendLine($"            component.{field.Name} = action.{field.Name};");
                sb.AppendLine("        }");
                sb.AppendLine("    }");
                sb.AppendLine("");
            }

            // 3. Generate Component Extension Methods
            sb.AppendLine("    public static partial class ComponentExtension");
            sb.AppendLine("    {");
            foreach (var field in info.Fields)
            {
                var actionName = $"Set{field.Name}Action";
                var componentFullName = info.StructName;
                var fieldType = field.Type;
                var paramName = char.ToLower(field.Name[0]) + field.Name.Substring(1);

                sb.AppendLine($"        public static void Set{field.Name}(this {componentFullName} component, {fieldType} {paramName}, Context ctx)");
                sb.AppendLine("        {");
                sb.AppendLine($"            ctx.Schedule(new {actionName}({paramName}), ctx.Entity);");
                sb.AppendLine("        }");
            }
            sb.AppendLine("    }");

            sb.AppendLine("}");

            context.AddSource($"{info.StructName}_AutoActions.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        // Standard stable hash code for strings (better cross-platform consistency than string.GetHashCode)
        private static int GetStableHashCode(string str)
        {
            unchecked
            {
                int hash1 = 5381;
                int hash2 = hash1;

                for (int i = 0; i < str.Length && str[i] != '\0'; i += 2)
                {
                    hash1 = ((hash1 << 5) + hash1) ^ str[i];
                    if (i == str.Length - 1 || str[i + 1] == '\0')
                        break;
                    hash2 = ((hash2 << 5) + hash2) ^ str[i + 1];
                }

                return hash1 + (hash2 * 1566083941);
            }
        }

        private class ComponentInfo
        {
            public string Namespace { get; set; } = "";
            public string StructName { get; set; } = "";
            public List<FieldInfo> Fields { get; set; } = new();
        }

        private class FieldInfo
        {
            public string Name { get; set; } = "";
            public string Type { get; set; } = "";
        }
    }
}
