using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Deterministic.GameFramework.SourceGenerators;

[Generator]
public class ComponentModelGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Check if the ReactiveSystem type exists in the compilation
        var reactiveSystemRef = context.CompilationProvider.Select((compilation, _) => 
            compilation.GetTypeByMetadataName("Deterministic.GameFramework.Reactive.ReactiveSystem") != null);

        // Find all structs that implement IComponent
        var components = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: (node, _) => node is StructDeclarationSyntax,
                transform: (ctx, _) => GetComponentInfo(ctx))
            .Where(m => m != null);

        // Combine components with the check
        var componentsWithCheck = components.Combine(reactiveSystemRef);

        // Generate the models only if ReactiveSystem exists
        context.RegisterSourceOutput(componentsWithCheck, (spc, source) => 
        {
            if (source.Right) // Right is the boolean result of the check
            {
                Execute(spc, source.Left);
            }
        });

        // Generate the shared ComponentExtensions
        var extensions = components.Collect().Combine(reactiveSystemRef);
        context.RegisterSourceOutput(extensions, (spc, source) => 
        {
            if (source.Right)
            {
                ExecuteExtensions(spc, source.Left);
            }
        });
    }

    private static ComponentInfo? GetComponentInfo(GeneratorSyntaxContext context)
    {
        var structDeclaration = (StructDeclarationSyntax)context.Node;
        var symbol = context.SemanticModel.GetDeclaredSymbol(structDeclaration);
        
        if (symbol == null) return null;

        // Check if implements IComponent
        if (!symbol.AllInterfaces.Any(i => i.Name == "IComponent"))
        {
            return null;
        }

        var namespaceName = symbol.ContainingNamespace.ToDisplayString();
        var structName = symbol.Name;
        
        var fields = symbol.GetMembers()
            .OfType<IFieldSymbol>()
            .Where(f => f.DeclaredAccessibility == Accessibility.Public && !f.IsStatic)
            .Select(f => new FieldInfo 
            { 
                Name = f.Name, 
                Type = f.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) 
            })
            .ToList();

        return new ComponentInfo
        {
            Namespace = namespaceName,
            StructName = structName,
            Fields = fields
        };
    }

    private void Execute(SourceProductionContext context, ComponentInfo? info)
    {
        if (info == null) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System;");
        sb.AppendLine("");
        sb.AppendLine("namespace Deterministic.GameFramework.Reactive");
        sb.AppendLine("{");
        
        var modelName = $"{info.StructName}Model";
        var viewModelName = $"{info.StructName}ViewModel";
        var structFullName = $"global::{info.Namespace}.{info.StructName}";
        
        // Generate Model
        sb.AppendLine($"    public class {modelName} : global::Deterministic.GameFramework.Reactive.Model");
        sb.AppendLine("    {");
        
        // Properties
        foreach (var field in info.Fields)
        {
            sb.AppendLine($"        public global::R3.ReactiveProperty<{field.Type}> {field.Name} {{ get; private set; }} = new();");
        }
        
        sb.AppendLine("");
        
        // Constructor
        sb.AppendLine($"        public {modelName}(global::Deterministic.GameFramework.Reactive.ReactiveSystem reactive, global::Deterministic.GameFramework.CoreV2.Context context)");
        sb.AppendLine("        {");
        
        foreach (var field in info.Fields)
        {
            sb.AppendLine($"            reactive.Subscribe(");
            sb.AppendLine($"                context.State,");
            sb.AppendLine($"                (s) => s.GetComponent<{structFullName}>(context.Entity).{field.Name},");
            sb.AppendLine($"                (s, val) =>");
            sb.AppendLine($"                {{");
            sb.AppendLine($"                    {field.Name}.Value = val;");
            sb.AppendLine($"                }});");
        }
        
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("");

        // Generate ViewModel
        sb.AppendLine($"    public class {viewModelName} : global::Deterministic.GameFramework.Reactive.ViewModel");
        sb.AppendLine("    {");
        
        foreach (var field in info.Fields)
        {
            sb.AppendLine($"        public global::R3.ReactiveProperty<{field.Type}> {field.Name} {{ get; private set; }}");
        }
        
        sb.AppendLine("");
        sb.AppendLine($"        public {viewModelName}({modelName} model)");
        sb.AppendLine("        {");
        foreach (var field in info.Fields)
        {
            sb.AppendLine($"            {field.Name} = model.{field.Name};");
        }
        sb.AppendLine("        }");
        sb.AppendLine("    }");

        sb.AppendLine("}");

        context.AddSource($"{info.StructName}Model.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private void ExecuteExtensions(SourceProductionContext context, System.Collections.Immutable.ImmutableArray<ComponentInfo?> components)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System;");
        
        sb.AppendLine("");
        sb.AppendLine("namespace Deterministic.GameFramework.Reactive");
        sb.AppendLine("{");
        sb.AppendLine("    public static partial class ComponentExtensions");
        sb.AppendLine("    {");
        sb.AppendLine("");

        foreach (var comp in components)
        {
            if (comp == null) continue;
            
            var modelName = $"{comp.StructName}Model";
            var structFullName = $"global::{comp.Namespace}.{comp.StructName}";
            
            sb.AppendLine($"        public static {modelName} AsModel(this {structFullName} component, global::Deterministic.GameFramework.CoreV2.Context context)");
            sb.AppendLine("        {");
            sb.AppendLine($"            return new {modelName}(global::Deterministic.GameFramework.Reactive.ReactiveSystem.Instance, context);");
            sb.AppendLine("        }");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("ComponentExtensions.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private class ComponentInfo
    {
        public string Namespace { get; set; } = "";
        public string StructName { get; set; } = "";
        public List<FieldInfo> Fields { get; set; } = new();
    }

    private class FieldInfo
    {
        public string Name { get; set; } = "";
        public string Type { get; set; } = "";
    }
}
