using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Deterministic.GameFramework.SourceGenerators;

[Generator]
public class EntityRefGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var entities = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: (node, _) => node is TypeDeclarationSyntax t && t.AttributeLists.Count > 0,
                transform: (ctx, _) => GetEntityInfo(ctx))
            .Where(m => m != null);

        context.RegisterSourceOutput(entities, (spc, info) => Execute(spc, info!));
    }

    private static EntityInfo? GetEntityInfo(GeneratorSyntaxContext context)
    {
        var typeDecl = (TypeDeclarationSyntax)context.Node;
        var symbol = context.SemanticModel.GetDeclaredSymbol(typeDecl);
        if (symbol == null) return null;

        var attr = symbol.GetAttributes().FirstOrDefault(a =>
            a.AttributeClass?.Name == "EntityDefinitionAttribute" ||
            a.AttributeClass?.Name == "EntityDefinition");
        if (attr == null) return null;
        if (attr.ConstructorArguments.Length == 0) return null;

        var arg = attr.ConstructorArguments[0];
        if (arg.IsNull || arg.Kind != TypedConstantKind.Array) return null;

        var components = new List<ComponentRef>();
        foreach (var val in arg.Values)
        {
            if (val.Value is not INamedTypeSymbol typeSymbol) continue;

            var typeName = typeSymbol.Name;
            var propertyName = typeName.EndsWith("Component")
                ? typeName.Substring(0, typeName.Length - "Component".Length)
                : typeName;

            components.Add(new ComponentRef
            {
                Namespace = typeSymbol.ContainingNamespace.ToDisplayString(),
                TypeName = typeName,
                PropertyName = propertyName,
            });
        }
        if (components.Count == 0) return null;

        var className = symbol.Name;
        var archetypeName = className.EndsWith("Definition")
            ? className.Substring(0, className.Length - "Definition".Length)
            : className;

        return new EntityInfo
        {
            Namespace = symbol.ContainingNamespace.ToDisplayString(),
            ArchetypeName = archetypeName,
            Components = components,
        };
    }

    private static void Execute(SourceProductionContext context, EntityInfo info)
    {
        var refStruct = $"{info.ArchetypeName}Ref";
        var archetype = $"{info.ArchetypeName}Archetype";
        var filterStruct = $"{info.ArchetypeName}ArchetypeFilter";
        var extClass = $"EntityWorld{info.ArchetypeName}ArchetypeExtensions";
        const string EntityWorldT = "global::Deterministic.GameFramework.ECS.EntityWorld";
        const string EntityT = "global::Deterministic.GameFramework.ECS.Entity";
        const string MaskFilterT = "global::Deterministic.GameFramework.ECS.MaskFilter";

        // Tag component for cheap candidate iteration: prefer the one whose stripped name
        // matches the archetype name (CowComponent -> Cow); else fall back to the first.
        var tagIndex = 0;
        for (var i = 0; i < info.Components.Count; i++)
        {
            if (info.Components[i].PropertyName == info.ArchetypeName) { tagIndex = i; break; }
        }
        var tag = info.Components[tagIndex];
        var tagFqn = $"global::{tag.Namespace}.{tag.TypeName}";

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {info.Namespace};");
        sb.AppendLine();

        sb.AppendLine($"public readonly ref partial struct {refStruct}");
        sb.AppendLine("{");
        sb.AppendLine($"    private readonly {EntityWorldT} _world;");
        sb.AppendLine($"    public readonly {EntityT} Entity;");
        sb.AppendLine();
        sb.AppendLine($"    internal {refStruct}({EntityWorldT} world, {EntityT} entity)");
        sb.AppendLine("    {");
        sb.AppendLine("        _world = world;");
        sb.AppendLine("        Entity = entity;");
        sb.AppendLine("    }");
        sb.AppendLine();
        foreach (var c in info.Components)
        {
            var fqn = $"global::{c.Namespace}.{c.TypeName}";
            sb.AppendLine($"    public ref {fqn} {c.PropertyName} => ref _world.GetComponent<{fqn}>(Entity);");
        }
        sb.AppendLine("}");
        sb.AppendLine();

        sb.AppendLine($"public partial class {archetype}");
        sb.AppendLine("{");
        sb.AppendLine($"    private {archetype}() {{ }}");
        sb.AppendLine();
        sb.AppendLine("    public static readonly global::System.Type[] Components =");
        sb.AppendLine("    {");
        foreach (var c in info.Components)
        {
            sb.AppendLine($"        typeof(global::{c.Namespace}.{c.TypeName}),");
        }
        sb.AppendLine("    };");
        sb.AppendLine();
        sb.AppendLine($"    public static bool TryResolve({EntityWorldT} world, {EntityT} entity, out {refStruct} result)");
        sb.AppendLine("    {");
        for (var i = 0; i < info.Components.Count; i++)
        {
            var c = info.Components[i];
            var fqn = $"global::{c.Namespace}.{c.TypeName}";
            var prefix = i == 0 ? "        if (" : "            || ";
            var suffix = i == info.Components.Count - 1 ? ")" : "";
            sb.AppendLine($"{prefix}!world.HasComponent<{fqn}>(entity){suffix}");
        }
        sb.AppendLine("        {");
        sb.AppendLine("            result = default;");
        sb.AppendLine("            return false;");
        sb.AppendLine("        }");
        sb.AppendLine($"        result = new {refStruct}(world, entity);");
        sb.AppendLine("        return true;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public static {filterStruct} Filter({EntityWorldT} world) => new {filterStruct}(world);");
        sb.AppendLine("}");
        sb.AppendLine();

        // Filter enumerable: candidates from the cheapest tag-component filter, then
        // per-element checks for the remaining required components. Yields the ref struct.
        sb.AppendLine($"public readonly struct {filterStruct}");
        sb.AppendLine("{");
        sb.AppendLine($"    private readonly {EntityWorldT} _world;");
        sb.AppendLine($"    public {filterStruct}({EntityWorldT} world) {{ _world = world; }}");
        sb.AppendLine();
        sb.AppendLine($"    public Enumerator GetEnumerator() => new Enumerator(_world);");
        sb.AppendLine();
        sb.AppendLine("    public ref struct Enumerator");
        sb.AppendLine("    {");
        sb.AppendLine($"        private readonly {EntityWorldT} _world;");
        sb.AppendLine($"        private {MaskFilterT}.Enumerator _inner;");
        sb.AppendLine();
        sb.AppendLine($"        internal Enumerator({EntityWorldT} world)");
        sb.AppendLine("        {");
        sb.AppendLine("            _world = world;");
        sb.AppendLine($"            _inner = world.Filter<{tagFqn}>().GetEnumerator();");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine($"        public {refStruct} Current => new {refStruct}(_world, _inner.Current);");
        sb.AppendLine();
        sb.AppendLine("        public bool MoveNext()");
        sb.AppendLine("        {");
        sb.AppendLine("            while (_inner.MoveNext())");
        sb.AppendLine("            {");
        if (info.Components.Count > 1)
        {
            sb.AppendLine("                var e = _inner.Current;");
            for (var i = 0; i < info.Components.Count; i++)
            {
                if (i == tagIndex) continue;
                var c = info.Components[i];
                var fqn = $"global::{c.Namespace}.{c.TypeName}";
                sb.AppendLine($"                if (!_world.HasComponent<{fqn}>(e)) continue;");
            }
        }
        sb.AppendLine("                return true;");
        sb.AppendLine("            }");
        sb.AppendLine("            return false;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();

        sb.AppendLine($"public static class {extClass}");
        sb.AppendLine("{");
        sb.AppendLine($"    public static bool TryResolve<TArchetype>(this {EntityWorldT} world, {EntityT} entity, out {refStruct} result)");
        sb.AppendLine($"        where TArchetype : {archetype}");
        sb.AppendLine($"        => {archetype}.TryResolve(world, entity, out result);");
        sb.AppendLine();
        sb.AppendLine($"    public static {filterStruct} Filter<TArchetype>(this {EntityWorldT} world)");
        sb.AppendLine($"        where TArchetype : {archetype}");
        sb.AppendLine($"        => {archetype}.Filter(world);");
        sb.AppendLine("}");

        context.AddSource($"{refStruct}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private class ComponentRef
    {
        public string Namespace { get; set; } = "";
        public string TypeName { get; set; } = "";
        public string PropertyName { get; set; } = "";
    }

    private class EntityInfo
    {
        public string Namespace { get; set; } = "";
        public string ArchetypeName { get; set; } = "";
        public List<ComponentRef> Components { get; set; } = new();
    }
}
