using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Deterministic.GameFramework.SourceGenerators
{
    [Generator]
    public class NetworkIdGenerator : ISourceGenerator
    {
        public void Initialize(GeneratorInitializationContext context)
        {
            context.RegisterForSyntaxNotifications(() => new NetworkIdSyntaxReceiver());
        }

        public void Execute(GeneratorExecutionContext context)
        {
            if (!(context.SyntaxReceiver is NetworkIdSyntaxReceiver receiver))
                return;

            var typeIdMap = new Dictionary<string, int>();

            foreach (var typeDeclaration in receiver.CandidateTypes)
            {
                var semanticModel = context.Compilation.GetSemanticModel(typeDeclaration.SyntaxTree);
                if (semanticModel.GetDeclaredSymbol(typeDeclaration) is INamedTypeSymbol typeSymbol)
                {
                    var attributes = typeSymbol.GetAttributes();
                    var networkIdAttr = attributes.FirstOrDefault(a => a.AttributeClass?.Name == "NetworkIdAttribute" || a.AttributeClass?.Name == "NetworkId");

                    if (networkIdAttr != null && networkIdAttr.ConstructorArguments.Length > 0)
                    {
                        if (networkIdAttr.ConstructorArguments[0].Value is int id)
                        {
                            typeIdMap[typeSymbol.ToDisplayString()] = id;
                        }
                    }
                }
            }

            if (typeIdMap.Count == 0) return;

            string assemblyName = context.Compilation.AssemblyName?.Replace(".", "") ?? "Default";

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("");
            sb.AppendLine($"namespace Deterministic.GameFramework.Generated.{assemblyName}");
            sb.AppendLine("{");
            sb.AppendLine("    public static class NetworkIdRegistry");
            sb.AppendLine("    {");
            sb.AppendLine("        public static readonly Dictionary<Type, int> TypeToId = new Dictionary<Type, int>()");
            sb.AppendLine("        {");

            foreach (var kvp in typeIdMap)
            {
                sb.AppendLine($"            {{ typeof({kvp.Key}), {kvp.Value} }},");
            }

            sb.AppendLine("        };");
            sb.AppendLine("");
            sb.AppendLine("        public static readonly Dictionary<int, Type> IdToType = new Dictionary<int, Type>()");
            sb.AppendLine("        {");

            foreach (var kvp in typeIdMap)
            {
                sb.AppendLine($"            {{ {kvp.Value}, typeof({kvp.Key}) }},");
            }

            sb.AppendLine("        };");
            sb.AppendLine("");
            sb.AppendLine("        public static int GetId<T>() => TypeToId[typeof(T)];");
            sb.AppendLine("        public static Type GetType(int id) => IdToType[id];");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            context.AddSource("NetworkIdRegistry.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }
    }

    class NetworkIdSyntaxReceiver : ISyntaxReceiver
    {
        public List<TypeDeclarationSyntax> CandidateTypes { get; } = new List<TypeDeclarationSyntax>();

        public void OnVisitSyntaxNode(SyntaxNode syntaxNode)
        {
            if (syntaxNode is TypeDeclarationSyntax typeDecl && typeDecl.AttributeLists.Count > 0)
            {
                if (typeDecl.AttributeLists.Any(al => al.Attributes.Any(a => a.Name.ToString().Contains("NetworkId"))))
                {
                    CandidateTypes.Add(typeDecl);
                }
            }
        }
    }
}